stages:
  download_data:
    cmd: python scripts/download_raw_data.py
    deps:
    - scripts/download_raw_data.py
    params:
    - data_source
    outs:
    - data/pipeline/raw
  process_data:
    cmd: python scripts/process_data.py
    deps:
    - data/pipeline/raw
    - scripts/process_data.py
    params:
    - processed_data_path
    - raw_data_path
    - test_size
    outs:
    - data/pipeline/processed
