stages:
  download_data:
    cmd: python scripts/download_raw_data.py
    deps:
    - scripts/download_raw_data.py
    params:
    - data_source
    - raw_data_path
    - raw_filename
    outs:
    - data/pipeline/raw
  process_data:
    cmd: python scripts/process_data.py
    deps:
    - data/pipeline/raw
    - scripts/process_data.py
    params:
    - processed_data_path
    - raw_data_path
    - raw_filename
    - test_size
    outs:
    - data/pipeline/processed
  train:
    cmd: python scripts/train.py
    deps:
    - data/pipeline/processed
    - scripts/train.py
    params:
    - C
    - max_iters
    - model_path
    - processed_data_path
    - random_state
    outs:
    - model/model.pkl
  evaluation:
    cmd: python scripts/evaluation.py
    deps:
    - data/pipeline/processed
    - model/model.pkl
    - scripts/evaluation.py
    params:
    - model_path
    - processed_data_path
