n_estimators: 100
max_iters: 1000
C: 1.0
random_state: 42
test_size: 0.2
data_source: 'twitter-genderbias'
processed_data_source: 'data/processed/processed_iris.csv'
test_data_path: 'data/processed/test_iris.csv'
model_path: 'model/model.pkl'
