n_estimators: 100
max_iters: 200
C: 1.0
random_state: 42
test_size: 0.2
data_source: 'argilla/twitter-genderbias'
raw_data_path: '../data/raw/twitter-genderbias.csv'
processed_data_path: '../data/processed'
test_data_path: 'data/processed/test_iris.csv'
model_path: 'model/model.pkl'
